### ISSUE TITLE
Impromtu code review

### ISSUE THREAD

**Issue by dali99** [iOknes/ProjectEuler#1]
https://github.com/iOknes/ProjectEuler/blob/4e955585f824d12e83121cae64850d9c925abcef/Problem%201/main.c#L6
Du trenger ikke dynamic memory allocation for å lage arays:
```C
int a[n] = {0};
```
Skal heller ikke være redd for at det ligger noe annet enn 0 der hvis du intitalizer det.

https://github.com/iOknes/ProjectEuler/blob/4e955585f824d12e83121cae64850d9c925abcef/Problem%201/main.c#L8-L15
begge disse branchene gjør akuratt det samme:
```
if (i % 3 == 0 || i % 5 == 0) {
    a[a_idx] = i;
    a_idx++;
}
```

https://github.com/iOknes/ProjectEuler/blob/4e955585f824d12e83121cae64850d9c925abcef/Problem%201/main.c#L11-L12
pls ikke knekk `else if`s, da får dem veldig vondt i ryggen :(

https://github.com/iOknes/ProjectEuler/blob/4e955585f824d12e83121cae64850d9c925abcef/Problem%201/main.c#L17-L19
er litt rart kanskje å loope over ting, lagre det i et array, også loope over arrayet igjen for å få det du leter etter. Kunne du ikke ha gjort noe som:
```
for (int i = 1; i < N; i++) {
    if (i % 3 == 0 || i % 5 == 0) {
        a_idx++;
        sum += i
    }
}
```
også droppe mellomlagringen i arrayet? Er ikke farlig det da.

Lenge siden jeg har sett deg nå!
Daniel

**Comment by iOknes** [comment]
Implemented loop from last comment.

Ja, veldig lenge siden nå. Håper det går bra med deg.
-Iver
